name: ITAS 276 DevSecOps Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Add permissions at the workflow level
permissions:
  security-events: write  # Required for uploading SARIF files to Code Scanning
  actions: read          # Needed to access workflow run details
  contents: read         # Needed to checkout code

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Send start message to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Actions"
          embed-title: "🚀 Pipeline Started"
          embed-description: "A new workflow has started for [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-author-name: "${{ github.triggering_actor }}"
  
  build:
    runs-on: ubuntu-latest
    needs: notify-start
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: echo "Installing dependencies..."

      - name: Run tests
        run: echo "Running tests..."

      - name: Notify Discord - Build Completed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Actions"
          embed-title: "✅ Build Completed"
          embed-description: "The build has successfully completed."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    needs: build
    
    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4

      - run: semgrep ci --sarif > semgrep-results.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload Semgrep SARIF results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-scan-results
          path: semgrep-results.sarif
          
      - name: Notify Discord - Semgrep Scan Completed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Actions"
          embed-title: "🔒 Semgrep Scan Completed"
          embed-description: "Semgrep has scanned the repository for vulnerabilities. [Download SARIF Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  sast-analysis:
    runs-on: ubuntu-latest
    needs: semgrep
    steps:
      - name: Run SAST Analysis
        run: echo "Performing Static Analysis..."

      - name: Upload SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: sarif-report
          path: Results.sarif

      - name: Notify Discord - SAST Completed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Actions"
          embed-title: "🔍 SAST Analysis Completed"
          embed-description: "Static Analysis has been performed. [Download SARIF Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  notify-complete:
    runs-on: ubuntu-latest
    needs: [sast-analysis]
    steps:
      - name: Send completion message to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Actions"
          embed-title: "🎉 Pipeline Completed"
          embed-description: "The workflow has completed successfully."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
