# Workflow for ITAS 276 DevSecOps Assignment 3: A cosmic journey through the pipeline galaxy!
name: ITAS 276 DevSecOps Pipeline

# Trigger the workflow when explorers push or pull to the main branch
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Grant permissions for our spaceship to upload artifacts and scan the cosmos
permissions:
  security-events: write  # For SARIF uploads to Code Scanning
  actions: read          # To access mission logs (workflow details)
  contents: read         # To beam up the repository code

jobs:
  # Job 1: Launch the pipeline into orbit with a cosmic announcement
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Send launch message to Mission Control (Discord)
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}  # Secret coordinates to Discord galaxy
          username: "Starship Commander"  # Our fearless pipeline leader
          avatar-url: "https://i.imgur.com/8J9z9qK.png"  # A cool spaceship avatar (public image)
          embed-title: "🌌 Pipeline Launch Initiated!"
          embed-description: "Starship [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}) is blasting off! Commit: `${{ github.event.head_commit.message }}`"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-author-name: "Pilot: ${{ github.triggering_actor }}"  # The brave soul at the helm
  
  # Job 2: Build stage - Assemble the starship’s engines
  build:
    runs-on: ubuntu-latest
    needs: notify-start  # Awaits launch clearance
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Teleports code aboard

      - name: Install dependencies
        run: echo "Installing dependencies..."  # Simulates engine assembly

      - name: Run tests
        run: echo "Running tests..."  # Checks if the thrusters work

      - name: Notify Discord - Engines Ready
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Starship Commander"
          avatar-url: "https://i.imgur.com/8J9z9qK.png"
          embed-title: "🛠️ Engines Online!"
          embed-description: "The build is complete—ready for warp speed! Status: *Nominal* 🌟"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  # Job 3: Semgrep stage - Scan for asteroid-sized vulnerabilities
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    needs: build  # Launches after engines are ready
    container:
      image: semgrep/semgrep  # Deploys the asteroid scanner
    if: (github.actor != 'dependabot[bot]')  # Ignores robotic probes
    steps:
      - uses: actions/checkout@v4  # Scans the cargo hold (code)

      - name: Run Semgrep scan
        run: semgrep ci --sarif > semgrep-results.sarif  # Probes for cosmic bugs
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}  # Access key to scanner tech

      - name: Upload Semgrep SARIF results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-scan-results  # Stores the asteroid map
          path: semgrep-results.sarif  # Path to the scan data
          
      - name: Notify Discord - Scan Complete
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Starship Commander"
          avatar-url: "https://i.imgur.com/8J9z9qK.png"
          embed-title: "🕵️‍♂️ Asteroid Scan Complete!"
          embed-description: "Semgrep has mapped vulnerabilities. [Download Cosmic Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})—hope it’s not a meteor shower!"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  # Job 4: Celebrate a successful mission with a galactic victory cry
  notify-complete:
    runs-on: ubuntu-latest
    needs: [semgrep]  # Lands after the scan is done
    steps:
      - name: Send victory message to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Starship Commander"
          avatar-url: "https://i.imgur.com/8J9z9qK.png"
          embed-title: "🏆 Mission Accomplished!"
          embed-description: "The pipeline has landed safely in the [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}) galaxy. All systems green! 🌍✨"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
